# -*- coding: utf-8 -*-
"""calculateseriescommissionsLK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HEcsHuNKdrbe9EZNSvLk3PLVjRVc6Fq5
"""

variable = str(input("Do you want to calculate a commission ? : "))
while variable == 'yes':
  personsales = float(input("The person's sales is : "))
  commisionrate = float(input("The commision rate is : "))
  commission = personsales*commisionrate
  print("The commission is :", str(commission))
  variable = str(input("Do you want to calculate another one ? : "))