# -*- coding: utf-8 -*-
"""for_loop_assignementsLK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gzsdpDgbhI8HxJbLaUZ_UUrgRkq2xRQ2
"""

#Vowels

sentence = input("Write a sentence : ")
vowels = ['a', 'e', 'i', 'o', 'u']
i = ''
j = 0
for i in sentence:
  if i in vowels:
    j = j + 1
  else:
    j = j
print("The number of vowel in this sentence is :", j)

#Multiplication Table

number = int(input("Which number do you want : "))
table = [1,2,3,4,5,6,7,8,9,10]
result = 0
for i in table:
  result = i * number
  print(f'{i} x {number} = {result}')


#Other way with while loop

#j = 1
#while j < 11:
  #i = j*number
  #j = j + 1
  #print(i)

#Dictionary

student_grades = {
    	"Alice": 85,
    	"Bob": 92,
    	"Charlie": 78,
    	"Diana": 88,
    	"Eve": 91
	}

#value = 0
#for value in student_grades.values():
  #print(value)

#And if we want the key it's the same reasoning

for name,grade in student_grades.items():
  print("Student name is", name, "and his grade is :", grade)

#Count odd and even numbers

number = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
i = 0
odd = 0
even = 0
list_even = []
list_odd = []
for i in number:
  remain = i % 2
  if remain == 0:
    even = even + 1
    list_even.append(i)
  else:
    odd = odd + 1
    list_odd.append(i)
print("The number of odd is :",odd)
print("Even numers are :", list_even)
print("The number of even is :",even)
print("Odd numbers are :", list_odd)

#Largest and smallest number without max and min

numbers = [3,5,7,2,8,-1,4]
index = 1
largest = numbers[index]
smallest = numbers[index]
i = 0
for i in numbers:
  if i < smallest:
    smallest = i
  elif i > largest:
    largest = i
print("The smallest number in the list is :", smallest)
print("The largest number in the list is :", largest)