# -*- coding: utf-8 -*-
"""Four_digitLK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iPRQlwzEHN_0hmkT-COdmc4WTv23NxzP
"""

four_digit = int(input("Enter a four digit integer :"))
new_digit = 0
sum = 0
if 1000< four_digit < 9999:
  while not four_digit<1:
    new_digit = four_digit % 10
    four_digit = four_digit // 10
    sum = new_digit + sum
    print(new_digit)
  print("The sum is :", sum)
else:
  print("Your input was not four digits. Quitting.")